#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
        then
                cd $OPENSHIFT_DATA_DIR
		mkdir logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_102 ]
        then
        	cd $OPENSHIFT_DATA_DIR
                wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http://www.oracle.com/; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.tar.gz"
                tar xvf jdk-8u102-linux-x64.tar.gz
                rm -f jdk-8u102-linux-x64.tar.gz
fi


