#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_102
export PATH=$JAVA_HOME/bin:$PATH

nohup $JAVA_HOME/bin/java -Xms384m -Xmx412m -jar $OPENSHIFT_DATA_DIR/crossfit-2.0.0.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --spring.profiles.active=openshift > ${OPENSHIFT_DIY_LOG_DIR}/crossfit.log 2>&1 &
