#!/bin/bash

set -x

rm -rf /tmp/syncgithub/ && mkdir -p /tmp/syncgithub/$OPENSHIFT_APP_NAME && cd /tmp/syncgithub/$OPENSHIFT_APP_NAME 
git init 
git remote add -f origin ~/git/$OPENSHIFT_APP_NAME.git/ 
git pull origin master 
git remote add -f github https://github.com/lgangloff/crossfit-2.0.git 
git checkout remotes/github/master .openshift 
git commit -m "Synchro hooks github & openshit" 
git push origin master